global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: development
    project: fleet-telemetry-hub

scrape_configs:
  - job_name: fleet-ingestion
    static_configs:
      - targets: ["ingestion:9090"]
    metrics_path: /metrics
    scheme: http

  - job_name: fleet-processor
    static_configs:
      - targets: ["processor:9090"]
    metrics_path: /metrics
    scheme: http

  - job_name: fleet-query
    static_configs:
      - targets: ["query:9090"]
    metrics_path: /metrics
    scheme: http

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
